### ISSUE TITLE
Program not recognizing reactor through compact machine.

### ISSUE THREAD

**Issue by NotTylr** [IceWolf777/Nuclearcraft-Reactor-UI-ControlPanel#1]
Is there any way to make the computer recognize the reactor while going through a compact machine the cable appears to work going through the port on the side of the compact machine although when running nReactorGUIStart it reports back "no primary nc_fission_reactor available"

**Comment by CastilloAnthony** [comment]
That is an excellent question. I have not personally tried to use this program from a different dimension like that, however I will start looking into this some time this week.

**Comment by CastilloAnthony** [comment]
I have tried to reproduce this issue a couple of times now and I cannot recreate it. The program works for me through a compact machine with cables running from the computer, to the compact machine, into it through a tunnel and finally connected to the reactor. I assume you are using the compact machine's "tunnel" item, right? And are you trying to use this for skyfactory4?

**Comment by NotTylr** [comment]
I am using it with the tunnel and I am using it on MC ETERNAL. Thank you for the reply.

**Comment by CastilloAnthony** [comment]
Can I see your reactor/wiring/computer setup? I've loaded up a creative world in MC Eternal and setup a rudimentary opencomputer -> compact machine -> nuclearcraft fission reactor system and it works as intended.
