### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Nightwhisper666** [IceWolf777/Nuclearcraft-Reactor-UI-ControlPanel#3]
Hey

I've been trying to get you program to work but sadly it doesn't seem to work.

![image](https://user-images.githubusercontent.com/82456433/114563075-5ec1e380-9c6f-11eb-9335-905ccada419b.png)

**Comment by simonairz** [comment]
Did you make sure that you connected the computer to the reactor before trying to start the program?

**Comment by CastilloAnthony** [comment]
You must connect the Nuclear Craft reactor to the computer before attempting to run the program.
